version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "MONGODB_URI=mongodb://mongo:27017/mercadoflux"
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:4.4.4
    ports:
      - "27017:27017"
